excluded: # paths to ignore during linting. Takes precedence over `included`.
- Carthage
- Pods
- PaymentSDKExample/PaymentSDKEarlGreyTests/EarlGrey.swift
disabled_rules: # rule identifiers to exclude from running
- trailing_whitespace
